### ISSUE TITLE
Forked Omae to add German/build mutlilang version

### ISSUE THREAD

**Issue by actcontpr** [HeyOmae/Omae1.0#1]
Hoi. Looks neat. I've forked it  to build a multi-lang version with language switcher on top of the original version 15e3819. Maybe I can completely decouple language with a seperate array, perhaps using some jQuery selector magic to fetch labels and translate them. That would be cool.
If I have some suggestions to help make multilang easyer, I'll let you know, OK?

Thanks for the great tool, btw.

**Comment by dethstrobe** [comment]
I'm actually working on updating Omae with a new version using AngularJS. If you want to check out the src branch, might be worth wild to check that out. Though I'll be trying to refactor that to use the programing style of a guy named John Papa...so that'll be a bit in flux soon...or I'll get lazy and just stick with the way it's set up now. I haven't decided yet.
